// components/sidebars/utils/GenericSidebar.tsx
import ImageTabs from "@/components/interactive/ImageTabs";
import { ImageTab } from "@/lib/util/types";

export default function GenericSidebar({
  children,
  title,
  image,
  imageVariations,
}: GenericSidebarProps) {
  return (
    <div className="min-w-[16rem]">
      <div className="flex flex-col gap-2 p-2 bg-muted rounded-md">
        <div className="p-2 bg-white/20 rounded-md">
          <h2 className="text-xl font-bold text-center">{title}</h2>
        </div>
        {(imageVariations && (
          <ImageTabs images={imageVariations ?? [{ url: image }]} />
        )) ||
          (image && <ImageTabs images={[{ url: image }]} />)}
        {children}
      </div>
    </div>
  );
}

export interface GenericSidebarProps extends React.PropsWithChildren {
  title: string;
  image?: string;
  imageVariations?: ImageTab[];
}

// src/components/sidebar/utils/GenericSidebar.svelte
<script lang="ts">
	import type { ImageTab } from '$lib/types';
	import ImageTabs from '../../interactive/ImageTabs.svelte';

	export let title: string;
	export let image: string | undefined = undefined;
	export let images: ImageTab[] | undefined = undefined;
</script>

<div class="min-w-[20rem] not-prose">
	<div class="flex flex-col gap-2 p-2 bg-muted rounded-md">
		<div class="p-2 bg-white/20 rounded-md">
			<h2 class="text-xl font-bold text-center">{title}</h2>
		</div>
		{#if images}
			<ImageTabs {images} />
		{:else if image}
			insert image
		{:else}
			No image provided
		{/if}
		<slot />
	</div>
</div>
