// src/components/sidebar/GunSidebar.svelte
<script lang="ts">
	import type { GunDefinition } from 'suroi/common/src/definitions/guns';
	import GenericSidebar from './utils/GenericSidebar.svelte';
	import { getSuroiImageLink, getSuroiKillfeedImageLink } from '$lib/suroi';
	import { FireMode } from 'suroi/common/src/constants';
	import InfoboxCol from './utils/InfoboxCol.svelte';
	import InfoboxRow from './utils/InfoboxRow.svelte';

	export let gun: GunDefinition;
</script>

<GenericSidebar
	title={gun.name}
	images={[
		{
			src: getSuroiImageLink(gun),
			title: 'Loot'
		},
		{
			src: getSuroiImageLink(gun, undefined, 'world'),
			title: 'World'
		},
		{
			src: getSuroiKillfeedImageLink(gun),
			title: 'Killfeed'
		}
	]}
>
	<InfoboxRow>
		<InfoboxCol title="Fire Mode">
			{FireMode[gun.fireMode]}
		</InfoboxCol>
		<InfoboxCol title="Ammo Type">
			<!-- TODO: Ammo icon -->
		</InfoboxCol>
		<InfoboxCol title="Capacity">{gun.capacity}</InfoboxCol>
	</InfoboxRow>
	<InfoboxRow>
		<InfoboxCol title="Reload">
			{gun.singleReload ? '1' : gun.capacity} in {gun.reloadTime}s
		</InfoboxCol>
		<InfoboxCol title="Firing Delay" abbr="Delay between shots">
			{gun.fireDelay}ms
		</InfoboxCol>
		<InfoboxCol
			title="Switch Delay"
			abbr="Cooldown between switching between this weapon and another"
		>
			{gun.switchDelay}ms
		</InfoboxCol>
	</InfoboxRow>

	{#if gun.fireMode === FireMode.Burst}
		<InfoboxRow>
			<InfoboxCol title="Burst Cooldown">
				{gun.burstProperties.burstCooldown}ms
			</InfoboxCol>
			<InfoboxCol title="Shots per Burst">
				{gun.burstProperties.shotsPerBurst} shots
			</InfoboxCol>
		</InfoboxRow>
	{/if}
	<InfoboxRow>
		<InfoboxCol title="Spread" abbr="Spread (angle of inaccuracy) when still">
			{gun.shotSpread}°
		</InfoboxCol>
		<InfoboxCol title="Move Spread" abbr="Spread (angle of inaccuracy when moving)">
			{gun.moveSpread}°{' '}
			<abbr title="When compared to normal spread">
				({gun.moveSpread - gun.shotSpread > 0 ? '+' : ''}
				{(gun.moveSpread - gun.shotSpread).toFixed(2)}°)
			</abbr>
		</InfoboxCol>
	</InfoboxRow>
</GenericSidebar>

// src/routes/sidebars/GunSidebar.tsx
import { FireMode } from "@suroi/common/src/constants";
import { GunDefinition } from "@suroi/common/src/definitions/guns";
import { SidebarUtils } from "src/components/articles/sidebar";

export default function GunSidebar({ object: gun }: { object: GunDefinition }) {
  return (
    <>
      <SidebarUtils.Row>
        <SidebarUtils.Column title="Fire Mode">
          {FireMode[gun.fireMode]}
        </SidebarUtils.Column>
        <SidebarUtils.Column title="Ammo Type">
          <img
            src={`/img/game/loot/${gun.ammoType}.svg`}
            alt={`${gun.ammoType} ammo`}
          />
        </SidebarUtils.Column>
        <SidebarUtils.Column title="Capacity">
          {gun.capacity}
        </SidebarUtils.Column>
      </SidebarUtils.Row>
      <SidebarUtils.Row>
        <SidebarUtils.Column title="Reload Time">
          {gun.capacity} in{" "}
          {gun.singleReload ? gun.capacity * gun.reloadTime : gun.reloadTime}s
        </SidebarUtils.Column>
        <SidebarUtils.Column title="Firing Delay">
          {gun.fireDelay}ms
        </SidebarUtils.Column>
        <SidebarUtils.Column title="Switch Delay">
          {gun.switchDelay}ms
        </SidebarUtils.Column>
      </SidebarUtils.Row>
      <SidebarUtils.Row>
        <SidebarUtils.Column title="Spread">
          {gun.shotSpread}°
        </SidebarUtils.Column>
        <SidebarUtils.Column title="Spread While Moving">
          {gun.moveSpread}°
        </SidebarUtils.Column>
      </SidebarUtils.Row>
      <SidebarUtils.Section title="Ballistics">
        <SidebarUtils.Row>
          <SidebarUtils.Column title="Damage">
            {gun.ballistics.damage}
          </SidebarUtils.Column>
          <SidebarUtils.Column title="Bullet Speed">
            {gun.ballistics.speed}
          </SidebarUtils.Column>
          <SidebarUtils.Column title="Range">
            {gun.ballistics.range}
          </SidebarUtils.Column>
        </SidebarUtils.Row>
        <SidebarUtils.Row>
          <SidebarUtils.Column title="Damage">
            {gun.ballistics.damage}
          </SidebarUtils.Column>
          <SidebarUtils.Column title="Bullet Speed">
            {gun.ballistics.speed}
          </SidebarUtils.Column>
          <SidebarUtils.Column title="Range">
            {gun.ballistics.range}
          </SidebarUtils.Column>
        </SidebarUtils.Row>
      </SidebarUtils.Section>
    </>
  );
}
